<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wondrous_forms"
 *
 * Auto generated by Extension Builder 2015-11-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Wondrous Forms',
	'description' => 'A Simple Form Plugin',
	'category' => 'plugin',
	'author' => 'Sebastian Thadewald',
	'author_email' => 'sebastian@wondrous.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.12',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);